name: Testing

on:
  issue_comment:
    types: [created]

jobs:
    setup:
        if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/prefix') }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/github-script@v7
          id: workspace-parser
          with:
            result-encoding: string
            script: |
                console.log('Jake context', context);
                const str = github.event.comment.body;
                const wsStr = str.replace('/prefix', '').trim().split(',');
                return wsStr.join(' ');
        - name: Get Results
          run: echo "${{steps.workspace-parser.outputs.result}}"