name: Testing

on:
  issue_comment:
    types: [created]

jobs:
    setup:
        if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/prefix') }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/github-script@v7
          id: workspace-parser
          with:
            result-encoding: string
            script: |
                const str = context.payload.comment.body;
                const wsStr = str.replace('/prefix', '').trim().split(',').filter(x => x.length !== 0).map(x => x.trim());

                if (!wsStr || wsStr.length === 0) {
                  core.setFailed(`No ws names provided. Please be sure the format of your comment is correct.`);
                  github.rest.issues.addLabels({
                    issue_number: context.payload.comment.id,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ['Failure', 'No Workspaces']
                  });
                }

                // validate string
                const allowed = ['one', 'two', 'three'];
                if (!wsStr.every(x => allowed.includes(x))) {
                  core.setFailed(`Invalid ws name provided, valid options are "${allowed.join(', ')}", provided: "${wsStr.join(', ')}"`);
                  github.rest.issues.addLabels({
                    issue_number: context.payload.comment.id,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ['Failure', 'Invalid Workspaces']
                  });
                }

                github.rest.issues.addLabels({
                  issue_number: context.payload.comment.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['Success']
                });
                return wsStr.map(x => x.trim()).join(' ');
        - name: Get Results
          run: echo "${{steps.workspace-parser.outputs.result}}"