name: Testing

on:
  issue_comment:
    types: [created]

jobs:
    setup:
        if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/prefix') }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/github-script@v7
          id: workspace-parser
          with:
            result-encoding: string
            script: |
                console.log('Jake context', context);
                const str = context.payload.comment.body;
                const wsStr = str.replace('/prefix', '').trim().filter(x => x.length !== 0).split(',');

                if (!wsStr || wsStr.length === 0) {
                  core.setFailed(`No ws names provided. Please be sure the format of your comment is correct.`)
                }

                // validate string
                const allowed = ['jake', 'one', 'two', 'three'];
                if (!wsStr.every(x => allowed.includes(x))) {
                  core.setFailed(`Invalid ws name provided, valid options are ${allowed.join(' ')}`)
                }

                return wsStr.map(x => x.trim()).join(' ');
        - name: Get Results
          run: echo "${{steps.workspace-parser.outputs.result}}"